#ifndef __MEDIONRADIOEXTENSIONS_H__
#define __MEDIONRADIOEXTENSIONS_H__
typedef enum api_event_t {
  API_EVENT_CHANNEL = 50,
  API_EVENT_SWITCH,
  API_EVENT_VOLUME,
  API_EVENT_LED,
  API_EVENT_START,
  API_EVENT_TONE_TOUCH = 15,
  API_EVENT_TONE_UNTOUCH = 0,
  API_EVENT_TONE_PRESSED = 1,
  API_EVENT_TONE_LONGPRESSED = 4,
  API_EVENT_TONE_LONGRELEASED = 7,
  
  API_EVENT_TONE_2PRESSED = 2,
  API_EVENT_TONE_2LONGPRESSED = 5,
  API_EVENT_TONE_2LONGRELEASED = 8,

  API_EVENT_TONE_3PRESSED = 3,
  API_EVENT_TONE_3LONGPRESSED = 6,
  API_EVENT_TONE_3LONGRELEASED = 9
};

extern void handleApiEvent(int event, uint32_t param, bool ignoreLock=false);
//extern bool executeCmdsFromNVSKey(const char *key, String value = "");


#endif
