#!/bin/bash
# usage:
# Parameter $1 "NAME" of the radio (used as Name of the Radio). Defines:
#               - name of the mqtt_topic (as $1/command)
#               - name of the output-file (as $1.mp3)
#               - as such, it must not contain any '/'
# Parameter $2 download-ID of the file (as attachment to the download-URL below)
# 
# can be called using xargs from i.e. MQTT-message with parameters separated by spaces:
#     mosquitto_sub -t "radioalerts" | xargs -L1 ./alermaker

echo "Parameter1=$1"
echo "Parameter2=$2"

downloadurl="http://hcuc9yjisphkpbzs.myfritz.net:2412/radio/"
uploadurl="hcuc9yjisphkpbzs.myfritz.net:2412/radioalerts/"
downloadfile="/share/www/radioalerts/$1.ogg"
uploadfile="/share/www/radioalerts/$1.mp3"
if [ $1 = "oparadio" ]; then
    mosqpub_params="-h 192.168.194.91 -p 18883 -u admin -P mgb027"
    echo "Oparadio"
else
    echo "Kein Oparadio"
    mosqpub_params="-h raspberrypi.fritz.box"
fi

echo "wget -O $downloadfile $downloadurl$2"
wget -O $downloadfile $downloadurl$2

ffmpeg -y -i $downloadfile $uploadfile

rm $downloadfile

uploadfileurl=$uploadurl$1.mp3

echo "mosquitto_pub $mosqpub_params -t $1/command -m alert=$uploadfileurl"

mosquitto_pub $mosqpub_params -t $1/command -m alert=$uploadfileurl